### ISSUE TITLE
[BUG] "Could not find the language, did you forget to load/include a language module?"

### ISSUE THREAD

**Issue by calejvaldez** [Fechin/reference#619]
I'm trying to create a new cheatsheet, but when I run `npm run dev`, I get various errors. I'm not sure how to continue.

This is the output:

```plaintext
> CheatSheets.zip@1.0.0 dev
> run-p dev:*


> CheatSheets.zip@1.0.0 dev:css
> npx postcss themes/coo/source/css/style.tailwindcss -o themes/coo/source/css/style.css --watch


> CheatSheets.zip@1.0.0 dev:hexo
> npx hexo clean && npx hexo server

INFO  Validating config
(node:47719) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
INFO  Deleted database.

warn - Your `content` configuration includes a pattern which looks like it's accidentally matching all of `node_modules` and can cause serious performance issues.
warn - Pattern: `./**/*.md`
warn - See our documentation for recommendations:
warn - https://tailwindcss.com/docs/content-configuration#pattern-recommendations
INFO  Validating config
(node:47773) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
INFO  Start processing
[Browsersync] Access URLs:
 ----------------------------------
          UI: http://localhost:3001
 ----------------------------------
 UI External: http://localhost:3001
 ----------------------------------
Could not find the language 'pug', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'mongosh', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTex', did you forget to load/include a language module?
Could not find the language 'KaTex', did you forget to load/include a language module?
Could not find the language 'KaTex', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'KaTeX', did you forget to load/include a language module?
Could not find the language 'regex', did you forget to load/include a language module?
FATAL {
  err: TypeError: Cannot read properties of null (reading 'colsnum')
      at Object.transform (/home/calejvaldez/git/open/reference/node_modules/markdown-it-attrs/patterns.js:175:39)
      at Array.curlyAttrs (/home/calejvaldez/git/open/reference/node_modules/markdown-it-attrs/index.js:87:19)
      at Core.process (/home/calejvaldez/git/open/reference/node_modules/hexo-renderer-markdown-it/node_modules/markdown-it/lib/parser_core.js:51:13)
      at MarkdownIt.parse (/home/calejvaldez/git/open/reference/node_modules/hexo-renderer-markdown-it/node_modules/markdown-it/lib/index.js:523:13)
      at MarkdownIt.render (/home/calejvaldez/git/open/reference/node_modules/hexo-renderer-markdown-it/node_modules/markdown-it/lib/index.js:543:36)
      at module.exports (/home/calejvaldez/git/open/reference/node_modules/hexo-renderer-markdown-it/lib/renderer.js:42:17)
      at Hexo.tryCatcher (/home/calejvaldez/git/open/reference/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.<anonymous> (/home/calejvaldez/git/open/reference/node_modules/bluebird/js/release/method.js:15:34)
      at /home/calejvaldez/git/open/reference/node_modules/hexo/lib/hexo/render.js:75:22
      at tryCatcher (/home/calejvaldez/git/open/reference/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/calejvaldez/git/open/reference/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/calejvaldez/git/open/reference/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/home/calejvaldez/git/open/reference/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/home/calejvaldez/git/open/reference/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/calejvaldez/git/open/reference/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/calejvaldez/git/open/reference/node_modules/bluebird/js/release/async.js:102:5)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

**Comment by yiiman-dev** [comment]
Hello @calejvaldez,
The issue has been resolved.
Kindly try again and provide your feedback here.

**Comment by calejvaldez** [comment]
Hi,

I pulled from the `main` branch and ran `npm i; npm run dev`. I get the same "Could not find the language" errors, but I can successfully start and use the development server. Not sure if the errors are important, though.

**Comment by Fechin** [comment]
Issue resolved: [c9a015b2b76dab41ad8197296473792098781be9](https://github.com/Fechin/reference/commit/c9a015b2b76dab41ad8197296473792098781be9)
